---
- name: Install node and npm
  hosts: 157.230.5.162 
  tasks:
   - name: Update apt repo and cache
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   - name: Install nodejs and npm
     apt:
        pkg: 
          - nodejs
          - npm


- name: Create new linux user for node app
  # replace with your host IP address
  hosts: 157.230.5.162
  tasks:
    - name: Create linux user
      user:
      # replace with your username
        name: ashiwaju
        comment: ashiwaju admin
        group: admin

- name: Deploy nodejs app
  hosts: 157.230.5.162
  become: True
  become_user: ashiwaju
  vars:
    - location: /root/nodejs-app
    - version: 1.0.0
    - destination: /home/ashiwaju
  tasks: 
    - name: Copy nodejs folder to a server
      copy:
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{destination}}/app-1.0.0.tgz"
    - name: Unpack the nodejs file
      unarchive:
        src: "{{destination}}/app-1.0.0.tgz"
        dest: "{{destination}}"
        remote_src: yes
      
    - name: Install dependencies
      npm:
        path: "{{destination}}/package"
    - name: Start the application
      command: 
        chdir: "{{destination}}/package/app"
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}


